export const actionSearch = {
    INIATE_SEARCH_REQUEST: 'INIATE_SEARCH_REQUEST',
    INIATE_SEARCH_SUCCESS: 'INIATE_SEARCH_SUCCESS',
    INIATE_SEARCH_FAILURE: 'INIATE_SEARCH_FAILURE',
    SAVE_SEARCH_RESULT:    'SAVE_SEARCH_RESULT'
}